### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AuxiaoXD** [AneryCoft/AutoXGP#10]
Traceback (most recent call last):
  File "C:\Users\Liquid_lol\Desktop\AutoXGP-main\AutoXGP.py", line 842, in assign_account
    getXGP(account)
  File "C:\Users\Liquid_lol\Desktop\AutoXGP-main\AutoXGP.py", line 480, in getXGP
    pay_password:str = alipay_encrypt_js.call("securityPassword",alipay_pay_password,PK,TS)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liquid_lol\AppData\Local\Programs\Python\Python312\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 语法错误

**Comment by CookiesHax** [comment]
抱歉
因退款受到限制此项目不再维护
