### ISSUE TITLE
设置代号后报错

### ISSUE THREAD

**Issue by darkI33T** [AneryCoft/AutoXGP#5]
C:\Users\Administrator\Desktop\AutoXGP-main>python AutoXGP.py
[16:28:16] 已设置Xbox玩家代号为:drdcohCJ0otRzCd
Exception in thread Thread-3 (assign_account):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\AutoXGP-main\AutoXGP.py", line 814, in assign_account
    getXGP(account)
  File "C:\Users\Administrator\Desktop\AutoXGP-main\AutoXGP.py", line 595, in getXGP
    addressId = addresses.json()["id"]
                ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'id'

**Comment by CookiesHax** [comment]
@AneryCoft 主播处理下这个

**Comment by Tuffy163** [comment]
#6 This one might help you
